### ISSUE TITLE
Hit raise ImportError("Failed to import any qt binding"), Matplotlib/backends/qt_compat.py:165

### ISSUE THREAD

**Issue by mdgith** [udacity/CarND-Camera-Calibration#2]
I cloned the project onto my local machine and then ran the Jupyter notebook, and hit the error, 
   raise ImportError("Failed to import any qt binding"), Matplotlib/backends/qt_compat.py:165
when executing %matplotlib qt
Is this because of my environment, or something else?

**Comment by mvirgo** [comment]
This is likely environment related - please note that these types of questions should be posted in Knowledge or Student Hub, not the Waffle board.

Try `pip install PyQt5` (or it may also be under `python-pyqt5`). Otherwise you might try the solution [here](https://stackoverflow.com/questions/52346254/importerror-failed-to-import-any-qt-binding-python-tensorflow) as well. Note that if this is within an Anaconda environment, you'll want to make sure to be running these while it is activated.
